/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_leicixiang_leitest_myJNI */

#ifndef _Included_cn_leicixiang_leitest_myJNI
#define _Included_cn_leicixiang_leitest_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_leicixiang_leitest_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_leicixiang_leitest_myJNI_sayHello
  (JNIEnv *env, jclass jobj){
    return (*env)->NewStringUTF(env, "WWW.LEICIXIANG.CN FROM JNI 2");
  }

#ifdef __cplusplus
}
#endif
#endif
